# Banco de Dados Manual de Entidades e Curiosidades Foda
# Este arquivo serve para alimentar o Ideator com temas que JÁ SABEMOS que são bons.

ENTIDADES_POR_NICHO = {
    "Games": [
        "The Last of Us Clicker sound design",
        "Shadow of the Colossus Team Ico secrets",
        "Super Mario 64 technical glitches",
        "Half-Life 2 development leak",
        "PlayStation 2 emotion engine design",
        "Pac-Man level 256 bug",
        "World of Warcraft corrupted blood plague",
        "Atari E.T. landfill excavation",
        "Polybius urban legend gaming",
        "Silent Hill fog hardware limits",
        "Doom 1993 source code history",
        "Final Fantasy VII production secrets",
        "P.T. Silent Hills PT hidden ghost",
        "GoldenEye 007 N64 development",
        "GTA San Andreas hot coffee scandal",
    ],
    "Ciência e Espaço": [
        "Voyager 1 Golden Record history",
        "Diamond Planet 55 Cancri e",
        "Wow! signal frequency mystery",
        "Juno mission Jupiter data",
        "Schrödinger cat experiment logic",
        "Tardigrades outer space survival",
        "Black hole M87 event horizon",
        "James Webb telescope first images",
        "The Great Attractor space mystery",
        "Saturn Hexagon storm explanation",
        "Mars Curiosity rover findings",
        "Enceladus ocean plumes science",
        "Tabby's Star dimming mystery",
        "Neutron star collision facts",
        "Dark Matter discovery evidence",
    ],
    "História e Mistérios": [
        "Antikythera Mechanism ancient computer",
        "Voynich Manuscript mystery",
        "Library of Alexandria history",
        "Tutankhamun mask archaeology",
        "Great Pyramid Giza alignment",
        "Lost City of Atlantis legend",
        "Easter Island Moai statues history",
        "Roanoke Colony disappearance mystery",
        "Bermuda Triangle myth and reality",
        "Templar Knights history and myths",
        "Nazca Lines archaeological discovery",
        "Dead Sea Scrolls discovery history",
        "Stonehenge archaeological facts",
        "Piri Reis map history",
        "Terracotta Army archaeological discovery",
    ],
    "True Crime e Mistérios": [
        "D.B. Cooper hijacking mystery",
        "Zodiac Killer cipher history",
        "Black Dahlia Elizabeth Short",
        "Elisa Lam Cecil Hotel mystery",
        "Somerton Man case history",
        "Dyatlov Pass incident mystery",
        "Mary Celeste ghost ship mystery",
        "Jack the Ripper historical theories",
        "Cicada 3301 internet mystery",
        "The Watcher house story",
        "JonBenét Ramsey case facts",
        "H.H. Holmes murder castle",
        "Axeman of New Orleans history",
        "Green River Killer case details",
    ]
}

TEMAS_ESTRUTURADOS = [
    "O segredo por trás do som dos Clickers em The Last of Us",
    "Por que o PlayStation 2 tem esse design tão estranho?",
    "O erro matemático que quase destruiu a missão Apollo 11",
    "Como os cientistas descobriram um planeta feito de diamante",
    "O que realmente aconteceu com o mecanismo de Antikythera?",
    "A verdade sobre o código que ninguém consegue ler: Manuscrito Voynich",
    "O mistério da vila que desapareceu sem deixar rastros em 1587",
    "Como o nevoeiro de Silent Hill foi criado por causa de uma limitação técnica",
    "O glitch de Pac-Man que quebra o jogo no nível 256",
    "A mensagem escondida no disco de ouro da Voyager 1",
    "O que os cientistas encontraram no fundo do oceano de Encélado",
    "O mistério do sinal Wow! que nunca mais se repetiu",
]
